SYSTEM:
  NUM_GPUS: 1
MODEL:
  LOPT: [['DiceLoss', 'WeightedBCE'],['MSE'],['DiceLoss','WeightedBCE']]
  WOPT: ['']
  LOSS_WEIGHT: [[1.0,1.0],[1.0],[1.0,1.0]]
  INPUTSHAPE: [256, 256]
  OUTPUTSHAPE: [128, 128]
DATASET:
  INPUTPATH: ''
  IMAGE: '.json'
  LABEL: '.json'
INFERENCE:
  IMAGE: '.json'

SOLVER:
  LR_SCHEDULER: 'ReduceOnPlateau'
